version: 2

sources:
  - name: LOGISTICS_RAW
    database: AIRBYTE_DATABASE
    schema: LOGISTICS
    tables:
    - name: customers
      description: Customer dimension
      columns:
        - name: CUSTOMER_ID
          tests:
          - not_null
          - unique
        - name: EMAIL
          tests:
            - not_null

    - name: couriers
      description: Courier dimension
      columns:
        - name: COURIER_ID
          tests:
            - not_null
            - unique
        - name: NAME
          tests:
            - not_null

    - name: inventory
      description: Inventory fact table
      columns:
        - name: ID
          tests:
            - not_null
            - unique
        - name: PRODUCT_ID
          tests:
            - not_null
            - relationships:
                to: ref('product')
                field: PRODUCT_ID
        - name: SELLER_ID
          tests:
            - not_null
            - relationships:
                to: ref('seller')
                field: SELLER_ID
        - name: STOCK
          tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: 0
                max_value: 5000
                strictly: true          

    - name: locations
      description: Location dimension
      columns:
        - name: LOCATION_ID
          tests:
            - not_null
            - unique
        - name: PINCODE
          tests:
            - not_null

    - name: orders
      description: Orders fact table
      columns:
        - name: ORDER_ID
          tests:
            - not_null
            - unique
        - name: CUSTOMER_ID
          tests:
            - not_null
            - relationships:
                to: ref('customers')
                field: CUSTOMER_ID
        - name: PRODUCT_ID
          tests:
            - not_null
            - relationships:
                to: ref('products')
                field: PRODUCT_ID

    - name: products
      description: Product dimension
      columns:
        - name: PRODUCT_ID
          tests:
            - not_null
            - unique
        - name: PRODUCT_NAME
          tests:
            - not_null

    - name: sellers
      description: Seller dimension
      columns:
        - name: SELLER_ID
          tests:
            - not_null
            - unique
        - name: SELLER_NAME
          tests:
            - not_null
